local Plug = require('plug')
Plug.begin('~/.config/nvim/plugged')

Plug('folke/tokyonight.nvim', { branch = 'main' })
Plug('phaazon/hop.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/nvim-cmp')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim', { tag = '0.1.1' })
Plug('glepnir/dashboard-nvim')
Plug('max397574/better-escape.nvim')
Plug('kyazdani42/nvim-tree.lua')
Plug('christoomey/vim-tmux-navigator')
Plug('akinsho/bufferline.nvim', { tag = 'v3.*' })

Plug.ends()

vim.cmd('colorscheme tokyonight-storm')

require('keymaps')
require('plugins/better-escape')
require('plugins/hop')
require('plugins/lualine')
require('plugins/nvim-tree')
require('plugins/telescope')
require('plugins/bufferline')