local Plug = require('plug')
Plug.begin('~/.config/nvim/plugged')
-- testings some
Plug('folke/tokyonight.nvim', { branch = 'main' })
Plug('nvim-lua/plenary.nvim')
Plug('nvim-treesitter/nvim-treesitter', { run = ':TSUpdate' })
Plug('github/copilot.vim')
Plug('phaazon/hop.nvim')
Plug('nvim-tree/nvim-web-devicons')
Plug('L3MON4D3/LuaSnip', { tag = 'v2.*', run = 'make install_jsregexp' })
Plug('neovim/nvim-lspconfig')
Plug('hrsh7th/nvim-cmp')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('NeogitOrg/neogit')
Plug('nvim-telescope/telescope.nvim', { branch = '0.1.x' })
Plug('nvim-telescope/telescope-fzf-native.nvim', { run = 'make' })
Plug('max397574/better-escape.nvim')
Plug('nvim-tree/nvim-tree.lua')
Plug('christoomey/vim-tmux-navigator')
Plug('akinsho/bufferline.nvim', { tag = '*' })
Plug('karb94/neoscroll.nvim')
Plug('onsails/lspkind.nvim')
Plug('nvimdev/dashboard-nvim')
Plug('Pocco81/auto-save.nvim')
Plug('folke/trouble.nvim')
Plug('echasnovski/mini.diff', { branch = 'stable' })
Plug('rcarriga/nvim-notify')
Plug('olimorris/codecompanion.nvim')
Plug('nvim-lualine/lualine.nvim')
Plug('nvim-flutter/flutter-tools.nvim')
Plug('folke/snacks.nvim')

Plug.ends()

vim.cmd('colorscheme tokyonight-storm')
vim.cmd('set number')

require('keymaps')
require('plugins.better-escape')
require('plugins.hop')
require('plugins.nvim-tree')
require('plugins.telescope')
require('plugins.bufferline')
require('plugins.treesitter')
require('plugins.neogit')
require('plugins.smooth-scroll')
require('plugins.lsp')
require('plugins.auto-save')
require('plugins.trouble')
require('plugins.mini')
require('plugins.copilot')
require('plugins.flutter')
require('plugins.cmp')
require('plugins.dashboard')
require('plugins.lualine')
require('plugins.notify')
require('plugins.snacks')
